fix

diff --git a/dataplatform/multiple_stacks/geoserver.yaml b/dataplatform/multiple_stacks/geoserver.yaml
--- a/dataplatform/multiple_stacks/geoserver.yaml
+++ b/dataplatform/multiple_stacks/geoserver.yaml
@@ -10,7 +10,7 @@ services:
       - -c
       - |
         sleep 20
-        sudo yum install openssh-clients
+        sudo yum install -y openssh-clients
         hdfs dfs -get /geoserver-data . 2> /tmp/hdfs_error.log
         if [ $? -ne 0 ]; then
           echo "Error occurred while getting data from HDFS geoserver-data folder"
@@ -20,19 +20,19 @@ services:
         sleep 600
         count=0
         while ! ping -c 1 geoserver &> /dev/null && [ $count -lt 100000 ]; do
-         echo "Geoserver container is not reachable, retrying in 10 seconds..."
-         sleep 10
-         count=$((count+1))
+          echo "Geoserver container is not reachable, retrying in 10 seconds..."
+          sleep 10
+          count=$((count+1))
         done
         if [ $count -eq 100000 ]; then
-         echo "Reached maximum retry limit, exiting..."
-         exit 1
+          echo "Reached maximum retry limit, exiting..."
+          exit 1
         fi
         echo "Geoserver container is reachable, proceeding with scp command"
         scp -r geoserver-data/data/* geoserver:/home/geoserver/data 2> /tmp/scp_error.log
         if [ $? -ne 0 ]; then
-         echo "Error occurred while copying data to geoserver container"
-         exit 1
+          echo "Error occurred while copying data to geoserver container"
+          exit 1
         fi
         echo "End scp data to geoserver container"
     deploy:
